### ISSUE TITLE
no start application

### ISSUE THREAD

**Issue by luckydevil13** [tomquirk/FlickrBox#7]
[andy@andy-pc FlickrBox]$ python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt
Collecting argh==0.26.2 (from -r requirements.txt (line 1))
  Using cached argh-0.26.2-py2.py3-none-any.whl
Collecting flickr-api==0.5 (from -r requirements.txt (line 2))
  Using cached flickr_api-0.5.tar.gz
Collecting httplib2==0.10.3 (from -r requirements.txt (line 3))
  Using cached httplib2-0.10.3.tar.gz
Collecting oauth==1.0.1 (from -r requirements.txt (line 4))
  Using cached oauth-1.0.1.tar.gz
Collecting oauth2==1.9.0.post1 (from -r requirements.txt (line 5))
  Using cached oauth2-1.9.0.post1-py2.py3-none-any.whl
Collecting pathtools==0.1.2 (from -r requirements.txt (line 6))
  Using cached pathtools-0.1.2.tar.gz
Collecting PyYAML==3.12 (from -r requirements.txt (line 7))
  Using cached PyYAML-3.12.tar.gz
Collecting six==1.11.0 (from -r requirements.txt (line 8))
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting watchdog==0.8.3 (from -r requirements.txt (line 9))
  Using cached watchdog-0.8.3.tar.gz
Installing collected packages: argh, oauth, flickr-api, httplib2, oauth2, pathtools, PyYAML, six, watchdog
  Running setup.py install for oauth ... done
  Running setup.py install for flickr-api ... done
  Running setup.py install for httplib2 ... done
  Running setup.py install for pathtools ... done
  Running setup.py install for PyYAML ... \
done
  Running setup.py install for watchdog ... done
Successfully installed PyYAML-3.12 argh-0.26.2 flickr-api-0.5 httplib2-0.10.3 oauth-1.0.1 oauth2-1.9.0.post1 pathtools-0.1.2 six-1.11.0 watchdog-0.8.3
(venv) [andy@andy-pc FlickrBox]$ 
(venv) [andy@andy-pc FlickrBox]$ python3 flickrbox.py
Traceback (most recent call last):
  File "flickrbox.py", line 11, in <module>
    import flickr_api as flickr
  File "/home/andy/FlickrBox/venv/lib/python3.6/site-packages/flickr_api/__init__.py", line 28
    except Exception, e:
                    ^
SyntaxError: invalid syntax

@tomquirk , could you please take a look?

**Comment by tomquirk** [comment]
hey @luckydevil13, 

The issue is because the current release of the python-flickr-api on pip is not compatible with python 3.

To fix the issue, you should grab the "bleeding edge" version of the API directly from Github.

```bash
pip uninstall flickr_api && pip install git+git@github.com:alexis-mignon/python-flickr-api.git
```

I'll update the `requirements.txt` for this project ASAP. I also contribute to the python-flickr-api so I'll try to get it updated on pip soon.

**Comment by luckydevil13** [comment]
@tomquirk thanks! got it!
